version: '3.9'

services:
  keycloak:
    build: .
    image: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: "start-dev --import-realm"